services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3009
    ports:
      - "3009:3009"
    deploy:
      resources:
        limits:
          cpus: 5
    networks:
      - 3d-hand-network

networks:
  3d-hand-network:
    driver: bridge

