services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3007
    ports:
      - "3007:3007"
    networks:
      - 3d-hand-network

networks:
  3d-hand-network:
    driver: bridge

